### ISSUE TITLE
Add azurerm-vscode-tools extension installer?

### ISSUE THREAD

**Issue by dragon788** [pascalberger/chocolatey-packages#112]
I may tackle this with a pull request, but just ran down the rabbit hole of finding your awesome extension installers for Chocolatey (I'm definitely a fan). It would be great to reply to the blog post that started me down that path with an easy one line Chocolatey install for getting the extension(s) and VS Code. Some of the other extensions you've packaged might also solve some other issues brought up in the blog post.

https://www.petri.com/using-vs-code-edit-azure-json-templates

**Comment by pascalberger** [comment]
Thanks for the suggestion. Sure, I can create a Chocolatey package for the Azure Resource Manager Tools extension later.

**Comment by pascalberger** [comment]
@dragon788 Azure Resource Manager Tools package is uploaded to chocolatey.org and awaiting moderation: https://chocolatey.org/packages/vscode-azurerm-tools/1.0.0
