### ISSUE TITLE
Check for VSCode Insiders

### ISSUE THREAD

**Issue by TylerLeonhardt** [pascalberger/chocolatey-packages#115]
I was looking at your vscode-powershell Chocolatey package and noticed that you didn't check for VSCode Insiders in it:
https://github.com/pascalberger/chocolatey-packages/blob/2b1f8581389f6a9f0e00c612cf503d5256dfa2a8/manual/vscode-powershell/tools/ChocolateyInstall.ps1#L2

I type `code-insiders --install-extension ...`.

**Comment by pascalberger** [comment]
I plan to add support for installations in insider builds in an upcoming version. The required logic has been implemented in the `chocolatey-vscode.extension` package with https://github.com/chocolatey-community/chocolatey-coreteampackages/pull/1320. Once this has been released I'll update this package to use the extension and push a new release

**Comment by pascalberger** [comment]
@TylerLeonhardt The `vscode-powershell` package has now the vsix embedded and supports installing the extension in regular and insider builds, as also system and user level installer. 

[Visual Studio Code PowerShell Extension 2019.5.0](https://chocolatey.org/packages/vscode-powershell/2019.5.0) has been pushed to chocolatey.org and is now awaiting moderation.
