### ISSUE TITLE
Add ms-vsts.team for vscode

### ISSUE THREAD

**Issue by richardlhughes** [pascalberger/chocolatey-packages#123]
Please add the package resource:

https://github.com/Microsoft/azure-repos-vscode/

Let me know if I can help.

**Comment by pascalberger** [comment]
@richardlhughes Thanks for the suggestion. I plan to create two package for this extension: One (`vscode-azurerepos`) that will install the latest version of the extension and let Visual Studio Code handle updating the extension, and another package (`vscode-azurerepos-latest`) which you can use if you want to manage the extension lifecycle with Chocolatey.

**Comment by pascalberger** [comment]
@richardlhughes Package for installing the latest version of the Azure Repos extension is now available on [chocolatey.org] and waiting for moderation.

Package for installing a specific version without auto updating will follow once https://github.com/Microsoft/vscode/issues/63903 is fixed and released
