### ISSUE TITLE
add dependency to vscode package

### ISSUE THREAD

**Issue by overag3** [pascalberger/chocolatey-packages#152]
Please can you add dependency to vscode package like another extension vscode package :
- https://community.chocolatey.org/packages/vscode-ruby#dependencies
- https://community.chocolatey.org/packages/chocolatey-vscode#dependencies
- https://community.chocolatey.org/packages/vscode-puppet#dependencies
- ...

Regards

**Comment by pascalberger** [comment]
Thanks for the suggestion. The VSCode packages in this repo work with either vscode or vscode-insiders package as mentioned in the notes and therefore can't have a dependency to the vscode pacakge.
